name: Security Scan

on: [push]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        version: latest  # Установите последнюю версию Semgrep
    
    - name: Run Semgrep security scan
      run: |
        semgrep --config rules.yaml tree/src/App.js
        export EXIT_CODE=$?
    
    - name: Abort commit if Semgrep found issues
      if: ${{ env.EXIT_CODE == 1 }}
      run: echo "Semgrep found issues. Aborting commit." && exit 1

    - name: Commit code
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Auto commit"
        git push
