name: Security Scan

on:
  push:
    paths:
      - 'tree/src/App.js'

jobs:
  security_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run Semgrep security scan
      uses: docker://returntocorp/semgrep
      with:
        args: semgrep --config rules.yaml tree/src/App.js
